### ISSUE TITLE
Script stops after website can't be reached.

### ISSUE THREAD

**Issue by Kristofferyx** [the-okn3/volafile-downloader#1]
Sometimes Volafile gets a little downtime, servers are restarting i think. This make this script crasch, should'nt there be a "self-restart" feature? If the server is down, the script waits for 3-4~ minutes and restart itself. I know zero coding, but i have tried to implement this on my own with while True, unfortunatly without success.

[0908/190442.285:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared co
ntext.

DevTools listening on ws://127.0.0.1:12660/devtools/browser/e7bfa122-d0e3-4596-9
394-88ddcef5a10c
?[31m[-] The Website might be offline or another error occurred: Message:
?[0m

F:\volafile-downloader-master\volafile-downloader>

**Comment by the-okn3** [comment]
Hi Kristoffer, I will try to implement it this weekend :)

**Comment by Kristofferyx** [comment]
Awesome! Are you by any chance, adding the possibility to enter password protected rooms also?

**Comment by the-okn3** [comment]
I will look into it also.
PS: I replied to your e-mail, and sorry for the late reply

**Comment by the-okn3** [comment]
Done, closing this issue
